//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFWDatamigrationApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Claim2
    {
        public int ClaimId { get; set; }
        public string ClaimName { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<decimal> ClaimAmount { get; set; }
    }
}
