//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFWDatamigrationApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Claim3
    {
        public int ClaimId3 { get; set; }
        public string ClaimName3 { get; set; }
        public Nullable<System.DateTime> StartDate3 { get; set; }
        public Nullable<System.DateTime> EndDate3 { get; set; }
        public Nullable<decimal> ClaimAmount3 { get; set; }
    }
}
