//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFWDatamigrationApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class VolvoProgram
    {
        public int VolvoProgramId { get; set; }
        public string Programname { get; set; }
        public Nullable<System.DateTime> EnableDate { get; set; }
    }
}
